version: "3.9"

networks:
  carverse-net:
    driver: bridge

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carverse
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - carverse-net

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    restart: always
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - carverse-net

  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: always
    depends_on:
      - discovery-service
    ports:
      - "7003:7003"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - carverse-net

  chat-service:
    build: ./chat-service
    container_name: chat-service
    restart: always
    depends_on:
      - mysql
      - discovery-service
      - notification-service
    ports:
      - "7004:7004"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - carverse-net

volumes:
  mysql-data:
